"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

add_newline = false

format = """($nix_shell$container)$cmd_duration\
$os\
$hostname\
$localip\
$username \
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$directory\
$git_branch$git_commit$git_state$git_status$git_metrics\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$battery\
$time\
$character
"""

[character]
format = " $symbol "
success_symbol = "[○](green)"
error_symbol = "[x](red)"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:text"
disabled = true # Disabled by default

[username]
style_user = "yellow"
style_root = "purple"
format = "[$user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = ""
use_os_path_sep = true
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[cmd_duration]
format = "[◄ $duration ](text)"

[jobs]
format = "[$symbol$number]($style) "
style = "text"
symbol = "[▶](blue)"

[localip]
ssh_only = true
format = " [$localipv4](maroon) "
disabled = false

[time]
disabled = true
format = "[ $time]($style)"
utc_time_offset = "local"
use_12hr = true
style = "dimmed text"

[battery]
format = "[ $percentage$symbol]($style) "
full_symbol = "█"
charging_symbol = "[↑](bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"
disabled = true

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 60
style = "dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "dimmed yellow"

[git_branch]
format = "\\([$branch(:$remote_branch)]($style)"
style = "pink"

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = true

[git_status]
style = "pink"
format = "(|[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))\\)"
conflicted = "[✖](red)"
ahead = "[▴│[${count}](text)│](green)"
behind = "[▿│[${count}](text)│](red)"
diverged = "[◇ ▴┤[${ahead_count}](text)│▿┤[${behind_count}](text)│](maroon)"
untracked = "[…](yellow)"
stashed = "[◃◈](text)"
modified = "[✚$count](yellow)"
staged = "[●](yellow)"
renamed = "[»](blue)"
deleted = "[✕](red)"

[lua]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "yellow"

[nodejs]
format = '[ node ($version)]($style)'
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [${symbol}${version}]($style)"
symbol = "[⌉](blue)⌊ "
version_format = "${raw}"
style = "yellow"

[ruby]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "red"

[rust]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "red"

[package]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "dimmed yellow"

[swift]
format = " [${symbol}${version}]($style)"
style = "red"
version_format = "${raw}"

[aws]
format = " [$symbol $profile $region]($style)"
style = "blue"

[c]
format = " [$symbol($version(-$name))]($style)"

[docker_context]
format = "[$symbol$context]($style)"

[elixir]
format = " [$symbol $version OTP $otp_version ]($style)"

[golang]
format = " [$symbol($version )]($style)"

[haskell]
format = " [$symbol($version )]($style)"

[java]
format = " [${symbol}(${version} )]($style)"

[memory_usage]
format = " [${ram}( ${swap})]($style)"

[nix_shell]
style = 'dimmed blue'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed text)'
impure_msg = '[⌽](dimmed red)'
pure_msg = '[⌾](dimmed green)'
unknown_msg = '[◌](dimmed ellow)'

[os.symbols]
Arch = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"