"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$directory\

$fill \

$git_branch$git_commit$git_state$git_status$git_metrics\

$package\
$ruby\
$golang\
$lua\
$python\
$rust\
$nodejs\

$line_break\

$sudo\
$character"""

[character]
format = "$symbol "
success_symbol = "[❯](green)"
error_symbol = "[x](red)"

[directory]
truncation_length = 999
truncate_to_repo = false
read_only = ""
use_os_path_sep = true
style = "blue"
format = '[$path ]($style)'

[fill]
symbol = '-'
style = "dimmed black"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = ""
style = "pink"
only_attached = true

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = true

[git_status]
style = "pink"
conflicted = "[✖](red)"
untracked = "[…](yellow)"
modified = "[✚$count](yellow)"
staged = "[●](yellow)"
renamed = "[»](blue)"
deleted = "[✕](red)"

[lua]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "yellow"

[nodejs]
format = '[ node ($version)]($style)'
version_format = "${raw}"

[python]
format = " [${symbol}${version}]($style)"
symbol = "[⌉](blue)⌊ "
version_format = "${raw}"
style = "yellow"

[ruby]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "red"

[rust]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "red"

[package]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "dimmed yellow"

[golang]
format = " [$symbol($version )]($style)"

[sudo]
format = "[$symbol]($style)"
style = "bold bright-purple"
symbol = "⚡"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
