[tools]
go = "latest"
lua = "latest"
node = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"
python = "latest"
"gem:na" = "latest"
sops = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
